---------------------------------------------------------------
-- ALTER TABLE EMPLOYEES

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPARTMENTS_MANAGER_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ON DELETE SET NULL ENABLE;
