---------------------------------------------------------------
-- CREATE TRIGGER JOBS

CREATE OR REPLACE TRIGGER JOBS_BEFORE_INSERT 
BEFORE INSERT ON JOBS 
FOR EACH ROW
BEGIN
  IF :NEW.JOB_ID IS NULL THEN
    SELECT JOBS_SEQ.NEXTVAL INTO :NEW.JOB_ID FROM DUAL;
  END IF;
END;

