---------------------------------------------------------------
-- CREATE TRIGGER DEPARTMENTS

CREATE OR REPLACE TRIGGER DEPARTMENTS_BEFORE_INSERT 
BEFORE INSERT ON DEPARTMENTS 
FOR EACH ROW
BEGIN
 	IF :NEW.DEPARTMENT_ID IS NULL THEN
    SELECT DEPARTMENTS_SEQ.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
	END IF;
END;
/


CREATE OR REPLACE TRIGGER DEPARTMENTS_BEFORE_UPDATE 
BEFORE UPDATE ON DEPARTMENTS 
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

