---------------------------------------------------------------
-- CREATE TRIGGER EMPLOYEES

CREATE OR REPLACE TRIGGER EMPLOYEES_BEFORE_INSERT 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW
BEGIN
 	IF :NEW.EMPLOYEE_ID IS NULL THEN
    SELECT EMPLOYEES_SEQ.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
	END IF;
END;
/
