---------------------------------------------------------------
-- CREATE TABLE EMPLOYEES

CREATE TABLE EMPLOYEES 
(
  EMPLOYEE_ID NUMBER(7,0) NOT NULL
, FIRST_NAME NVARCHAR2(50)
, LAST_NAME NVARCHAR2(50)
, EMAIL VARCHAR2(100 CHAR) NOT NULL
, PHONE NUMBER
, HIRE_DATE DATE DEFAULT SYSDATE
, JOB_ID NUMBER NOT NULL
, SALARY NUMBER(8,2)
, MANAGER_ID NUMBER(5,0)
, DEPARTMENT_ID NUMBER(3,0)
, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    EMPLOYEE_ID
  )
  ENABLE 
);

