---------------------------------------------------------------
-- CREATE TABLE DEPARTMENNTS

CREATE TABLE DEPARTMENTS 
(
  DEPARTMENT_ID NUMBER(3,0) NOT NULL 
, DEPARTMENT_NAME NVARCHAR2(50) NOT NULL 
, MANAGER_ID NUMBER(7,0) NOT NULL 
, CREATED_AT TIMESTAMP DEFAULT systimestamp 
, UPDATED_AT TIMESTAMP DEFAULT systimestamp 
, CONSTRAINT DEPARTMENTS_PK PRIMARY KEY 
  (
    DEPARTMENT_ID 
  )
  ENABLE 
);

