---------------------------------------------------------------
-- CREATE SEQUENCES

CREATE SEQUENCE DEPARTMENTS_SEQ START WITH 1;
CREATE SEQUENCE EMPLOYEES_SEQ START WITH 1;
CREATE SEQUENCE JOBS_SEQ START WITH 1;

